version: '3'
services:

  game:
    build:
      context: .
      dockerfile: game/dockerfilegame
    image: dockergame/juraepuzzsagame:latest
    container_name: game
    restart: unless-stopped
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "9090:9090"
    networks:
      app-network:
        aliases:
          - game
  server:
    build:
      context: .
      dockerfile: databaseMS/dockerfile
    image: dockerserver/juraepuzzsaserver:latest
    container_name: server
    restart: unless-stopped
    tty: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8888:8888"
    depends_on:
      - game
    networks:
      app-network:
        aliases:
          - server

  redis:
    image: redis:4.0.14-alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    depends_on:
      - server
    networks:
      app-network:

networks:
  app-network: