FROM openjdk:11.0.2
ENV SBT_VERSION 1.2.8
ENV HOSTNAME serverdb
RUN \
  curl -L -o sbt-$SBT_VERSION.deb http://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get update && \
  apt-get install sbt && \
  sbt sbtVersion

WORKDIR /databaseMS

ADD . /databaseMS

CMD sbt "runMain ServerData.controller.Server"